#!/bin/sh
. ~/.bashrc

dir="$HOME/usr/local/"

mkdir -p $dir

n=0
rm -f ${dir}browser*.exe 2>/dev/null
while :
do
  if [ -f "${dir}browser${n}.exe" ]
  then
    let "n=n+1"
  else
    break
  fi
done
cp "$progcs/Browser/bin/Debug/browser.exe" ${dir}browser${n}.exe

if [ "$1" = '-g' ]
then
  ${dir}browser${n}.exe "$@"
else
  $HOME/usr/bin/browser.bat ${n} "$@"
fi
