#!/usr/bin/env bash
. ~/.bashrc

check() {
  $(ps -W | grep -i emacs.exe > /dev/null 2>&1)
  echo $?  
}

retcode=`check`
if [ $retcode != 0 ]; then
  echo + c:/emacs/bin/runemacs.exe
  c:/emacs/bin/runemacs.exe
  while :; do
    echo + sleep 1
    sleep 1
    retcode=`check`
    if [ $retcode = 0 ]; then
      break
    fi
  done
fi

args=("$@")
for i in "${!args[@]}"; do
  #printf "%s\t%s\n" "$i" "${args[$i]}"
  args[$i]=`cygdrivePathFix "${args[$i]}"`
  #printf "%s\t%s\n" "$i" "${args[$i]}"
done
set -- "${args[@]}"

gnuclientw "${@}"
