#!/usr/bin/env bash
. ~/.bashrc

# called from many dirs
#  => THIS SCRIPT
#    => mkshortcut.from.input.sh
#      => Cygwin/mkshortcut.exe

args=${1%getem.sh}
args=${args%.getem.sh}
#args=`echo ${1%.getem.sh} | sed -e 's:^#*::' -e 's:\.: :g' `
args=`echo $args | sed -e 's:^#*::' -e 's:\.: :g' `
if [ "$args" == "" ] ;then
  pwd="$PWD"
  while [ $(basename $pwd) != ==GEN ]; do
    arg="$(basename $pwd)"
    arg=${arg#@}
    arg=${arg,,}
    args="$args $arg"
    pwd=$(dirname $pwd)
  done
fi
echo args:$args:

findvid $args | grep -Eiv '(prproj$|lnk$|sh$)' | while read line; do
  bname=$(basename "$line")
  for arg in $args LAST_ITEM; do
    if [ "$arg" = LAST_ITEM ]; then
      echo $line
    else
      if [[ $bname =~ $arg ]]; then
        :
      else
        break
      fi
    fi
  done
done | mkshortcut.from.input.sh

mkdir -p _
for f in *.lnk; do
  if find . -type f | grep '/.*/' | grep "/$f" > /dev/null 2>&1 ; then
    # remove, since found in a sub-dir
    rm "$f"
  else
    :
    # keep, since not found in a sub-dir
  fi
done
