#!/usr/bin/env bash
. ~/.bashrc

args=`echo ${1%.getem.sh} | sed -e 's:^#*::' -e 's:\.: :g' `
echo args:$args:

for arg in $args ; do
  if [ -n "$args2" ]; then
    args2="${args2}"'|[^a-zA-Z]'"$arg"
  else
    args2='[^a-zA-Z]'"${arg}"'[^a-zA-Z]'
  fi
done
args2='('"${args2}"'[^a-zA-Z])'

findvid $args | grep -Eiv '(prproj$|lnk$|sh$)' | while read line; do
  bname=$(basename $line)
  for arg in $args LAST_ITEM; do
    if [ "$arg" = LAST_ITEM ]; then
      echo $line
    else
      if [[ $bname =~ $arg ]]; then
        :
      else
        break
      fi
    fi
  done
done | mkshortcut.from.input.sh

mkdir -p _
for f in *.lnk; do
  if find . -type f | grep '/.*/' | grep "/$f" > /dev/null 2>&1 ; then
    # remove, since found in a sub-dir
    rm "$f"
  else
    :
    # keep, since not found in a sub-dir
  fi
done
