#!/usr/bin/env bash
. ~/.bashrc

cd t:/Premiere.Pro.Work || o bitlocker || exit 1
\ls ./\#* > find 2>/dev/null
dir="t:/RECYCLABLE/v/"
cd $dir || o bitlocker || exit 1

find . -type f > find.txt

usage() {
  echo "usage: $(basename $0) [-d] -"
  echo "   or: $(basename $0) [-d] UID"
  echo "   or: $(basename $0) [-d] <SEARCH_STRING>..."
  echo "       -d: separate results by directory"
  echo "       -:  clipboard will hold a 'uid' number to look for"
  exit 1
}

if [ "$1" = "-d" ]; then
  separated=true
  shift
fi

if [ "$1" = "" ]; then
  usage
fi

if [ "$1" = '-' ]; then
  shift
  if [ $# != 0 ]; then
    usage
  fi
  set -- $(p)
  if [ $# != 1 ]; then
    echo "ERROR: clipboard contains more than one number"
    exit 1
  fi
  num=true
else
  if [ $# = 1 ]; then
    if [[ "$1" =~ ^[0-9]+$ ]]; then
      num=true
    fi
  fi
fi

if [ "$num" = true ]; then
  if [ $# != 1 ]; then
    echo "INTERNAL ERROR: should only be one arg!"
    exit 1
  fi
  num="$1"
  shift
  thing="$( echo $num | sed -e 's:[^#]*#::' -e 's:#.*::' -e 's:^:#:' -e 's:$:#:' )"
  set -- $( echo $num | sed -e 's:[^#]*#::' -e 's:#.*::' -e 's:^:#:' -e 's:$:#:' ) ${@}
fi

#echo ========================== 1>&2
#echo searching for: $@...       1>&2

args=''
for arg in "$@"; do
  args="${args}(?=.*$arg)"
done

old_d=""

if [ "$separated" != true ]; then
  cat find.txt t:/Premiere.Pro.Work/find | egrep -v '(jpg$|txt$|xmp$)' | grep -iP "$args" | grep '.*/' |
    sed -e 's|^\.|t:/RECYCLABLE/v|'
  exit
else
  cat find.txt t:/Premiere.Pro.Work/find | egrep -v '(jpg$|txt$)|xmp$' | grep -iP "$args" | sort |
  sed -e 's|^./|'$dir'|' |
  while read line; do
    f=${line##*/}
    d=${line%$f}
    if [ "$d" != "$old_d" ]; then
      echo '===================================================================='
      echo dd=\"$d\"
      old_d="$d"
    fi
    echo '  start "${dd}/'$f'"'
  done | egrep -i --color "$1|$"
fi
