#!/usr/bin/env bash

# This script is
#   ~/usr/bin/help
#
# It provides command completion when used in conjunction
#   ~/usr/bin/functions/completion/help
#

usage() {
  echo "usage: $(basename $0) TOPIC [e | SEARCH-ARGS]"
  echo "       e: edit the help file"
  exit 1
}

if [ "$#" = 0 ]; then
  usage
  exit
fi

if [ "$1" = -? ]; then
  cd ~/usr/bin/_help/; \ls -1 | sed -e 's:.org$::' | column
  exit
fi

file="$HOME/usr/bin/_help/${1}.org"
if [ ! -f "$file" ]; then
  echo "ERROR: Unknown option: \"$1\""
  echo 
  echo "  Try one of these:"
  $0 -? | expand | sed -e 's:^:  :'
  echo
  exit 1
fi
shift

if [ "$1" = "e" ] ; then
  edit=true
  shift
fi

if [ "$1" = "-i" ] ; then
  ignorecase=-i
  shift
fi

if [ "$edit" = 'true' ]; then
  if which gnuclientw >/dev/null 2>&1; then
    echo + gnuclientw "$file"
           gnuclientw "$file"
  else
    echo + emacsclient -nw "$file"
           emacsclient -nw "$file"
  fi     
  exit
fi

cat "$file" | if [ $# = 0 ]; then
  cat
else
  grepit=grep
  if ggrep > /dev/null 2>&1; then
      ggrep on Mac shows bold font for match; regular grep does not
      grepit=ggrep
  fi      
  $grepit $ignorecase --color=always -E "($|${@})"
fi
