#!/usr/bin/env bash

# convery python json-ish dictionarys to json

sed \
    -e "s:':\":g"          \
    -e 's:False:"False":g' \
    -e 's:True:"True":g'       |
  jq
#  jq -C | \
#    sed \
#    -e 's:"False":False:g' \
#    -e 's:"true":True:g'    