#!/usr/bin/env bash

cd ~/.ssh

if [ -f config ]; then
  mv config config_$(date "+%Y-%m-%d_%H:%M:%S")
fi

outf="config.LOCAL"
echo "creating ${outf}..." 1>&2
if [ `uname` = Darwin ]; then
  files="config.LOCAL.mac config.LOCAL.common"
else
  files="config.LOCAL.pc config.LOCAL.common"
fi
for file in $files
do
  echo "  from  $file..." 1>&2
  echo "#------------------------------------------------------------------------------"
  echo "#  This portion of $outf is from file \"$file\""
  echo "#------------------------------------------------------------------------------"
  cat $file
done > $outf

mv $outf ~/.ssh/config
